Module2 task1
htmlacademy-ecmascript/471547-big-trip-1 pull request #4
Opened 2024-03-12 06:55 UTC by kate-baidukova

2024-03-19 07:42 UTC, ademaro requested changes
Пока не закрываю, жду поправок, если хочется дальше — напиши, закрою ПР, поправки буду ждать по ходу разработки следующего функционала. В целом очень крутой код, молодец! 🔥 Всё чисто, с хорошим пониманием предметной области. Некоторые моменты обсудим голосом, есть что обсудить и о чём поговорить)

2024-03-19 07:42 UTC, ademaro commented on package.json
> +    "dayjs": "^1.11.10",
Версии зависимостей добавляем строгие (удаляем птичку)

2024-03-19 07:42 UTC, ademaro commented on package.json
> +    "dayjs": "^1.11.10",
Ну и в секцию зависимостей для приложения, а не для разработки логичнее поместить

2024-03-19 07:42 UTC, ademaro commented on package.json
> +    "flatpickr": "^4.6.13"
строгая версия

2024-03-19 07:42 UTC, ademaro commented on src/mock/const.js
> +const MAX_RANDOM_ID = 200;
можем пользоваться перечислениями для запаковки констант:
```js
const RandomId = {
  MIN: 1,
  MAX: 200
};
```

2024-03-19 07:42 UTC, ademaro commented on src/mock/const.js
> +/*
Удаляем сразу ненужный код

2024-03-19 07:42 UTC, ademaro commented on src/mock/const.js
> +const DATE_FORMAT = {
Константные значения — в основном примитивы (иногда массивы). Тут или перечисление или просто словарь (обычный объект без капса)

2024-03-19 07:42 UTC, ademaro commented on src/mock/mock-destination.js
> +import {getRandomArrayElement, getRandomId, getRandomInteger, getRandomNumber} from '../utils/util.js';
Моковые утилиты давай перенесём в папку моков, что бы не загрязнять основной код

2024-03-19 07:42 UTC, ademaro commented on src/mock/mock-destination.js
> +  const description = makeDescription ();
пробелы не ставятся в основном после названия ф-ции перед открывающей скобкой (как в определении, так и при вызове)

2024-03-19 07:42 UTC, ademaro commented on src/mock/mock-destination.js
> +    return {
можем чуть короче писать:
```js
{
  description,
  src: `https://loremflickr.com/248/152?random=${getRandomInteger(PHOTOS_RANDOM_COUNT)}`
}
```
Если название переменной для значения поля совпадает с названием поля — можем сокращать

2024-03-19 07:42 UTC, ademaro commented on src/mock/mock-destination.js
> +  const renderPhotos = Array.from({length: getRandomNumber (0, PHOTOS_COUNT)}, makePhoto);
render — больше глагол, по логике это у нас ф-ция. Но нет, это просто массив фоток. Плюс это вообще не про отрисовку, render можно убрать совсем) `photos` вполне достаточно было бы

2024-03-19 07:42 UTC, ademaro commented on src/model/offers-model.js
> +    this.service = service;
как по мне — слишком тесная связь с поставщиком данных, напомни — обсудим голосом в деталях, поделюсь мыслями)

2024-03-19 07:42 UTC, ademaro commented on src/presenter/main-presenter.js
> +export default class TripPresenter {
main presenter или всё-таки trip presenter?)) Переименуй или класс или файл

2024-03-19 07:42 UTC, ademaro commented on src/presenter/main-presenter.js
> +    this.points = [...this.pointsModel.get()];
расскажи зачем ты тут используешь spread?

2024-03-19 07:42 UTC, ademaro commented on src/presenter/main-presenter.js
> +    let offers = this.offersModel.getByType(type);
немного странно тут такое видеть) Предполагаю, что это нужно **только** для твоих View...

2024-03-19 07:42 UTC, ademaro commented on src/presenter/main-presenter.js
> +    for (let i = 1; i < this.points.length; i++) {
почему for? давай на forEach хотя бы...

2024-03-19 07:42 UTC, ademaro commented on src/presenter/main-presenter.js
> +      destinationId = this.points[i].length; i++;
со второй точки начинаешь — специально?

2024-03-19 07:42 UTC, ademaro commented on src/presenter/main-presenter.js
> +    for (let i = 1; i < this.points.length; i++) {
Давай начнём делать отдельные методы, например, `renderPoints()`

2024-03-19 07:42 UTC, ademaro commented on src/utils/util.js
> +import {DATE_FORMAT, MSEC_IN_DAY, MSEC_IN_HOUR} from '../mock/const.js';
Давай сделаем отдельные утилиты для приложения и отдельно — для моков

2024-03-19 07:42 UTC, ademaro commented on src/utils/util.js
> +  inputDate ? dayjs(inputDate).format(DATE_FORMAT.hourMinute) : '';
👍🏼

2024-03-19 07:42 UTC, ademaro commented on src/utils/util.js
> +      pointDuration = dayjs.duration(timeDiff).format('DD[D] HH[H] mm[M]');
можно было бы сразу сюда ставить return'ы, тогда и break даже не нужен бы был)

2024-03-19 07:42 UTC, ademaro commented on src/utils/util.js
> +      pointDuration = dayjs.duration(timeDiff).format('DD[D] HH[H] mm[M]');
но в таком случае if'ы читались бы ещё лаконичнее)

2024-03-19 07:42 UTC, ademaro commented on src/utils/util.js
> +  return function () {
смешение FE и FD — не очень, давай к единообразию

2024-03-19 07:42 UTC, ademaro commented on src/view/new-point-form-view.js
> +import {TYPE_ROUTE_POINTS, DATE_FORMAT} from '../mock/const.js';
от моков наши модули вообще не должны зависеть

2024-03-19 07:42 UTC, ademaro commented on src/view/new-point-form-view.js
> +  <div class="event__type-item">
отступы съехали, наведёшь красоту?)

2024-03-19 07:42 UTC, ademaro commented on src/view/new-point-form-view.js
> +      <input class="event__type-toggle  visually-hidden" id="event-type-toggle-1" type="checkbox">
`*-1` — не просто так, давай заменим на реальные идентификаторы, чтобы избежать проблем с возможной повторяемостью значений `id`-атрибутов в разметке...

2024-03-19 07:42 UTC, ademaro commented on src/view/trip-event-view.js
> +export default class TripEventElementView {
где-то point, где-то event, где-то event element и тд... Давай одну и ту же сущность называть везде одинаково, пройдись и по другим сущностям, что бы почистить небольшой бардак...

2024-03-19 15:50 UTC, kate-baidukova commented on package.json
> +    "flatpickr": "^4.6.13"
+

2024-03-19 15:50 UTC, kate-baidukova commented on package.json
> +    "dayjs": "^1.11.10",
+

2024-03-19 16:06 UTC, kate-baidukova commented on src/mock/const.js
> +const MAX_RANDOM_ID = 200;
исправила, по аналогии сделала и для цен (парой строк ниже)

2024-03-19 16:07 UTC, kate-baidukova commented on src/mock/const.js
> +/*
снесла

2024-03-19 16:59 UTC, kate-baidukova commented on src/mock/mock-destination.js
> +import {getRandomArrayElement, getRandomId, getRandomInteger, getRandomNumber} from '../utils/util.js';
сделала + перенесла mock-service тоже в моки. Надеюсь, второе тоже окажется на пользу делу. Импорты исправила по файлам.

2024-03-19 17:21 UTC, kate-baidukova commented on src/mock/mock-destination.js
> +  const description = makeDescription ();
исправила

2024-03-19 17:26 UTC, kate-baidukova commented on src/mock/mock-destination.js
> +    return {
поправила

2024-03-19 17:28 UTC, kate-baidukova commented on src/mock/mock-destination.js
> +  const renderPhotos = Array.from({length: getRandomNumber (0, PHOTOS_COUNT)}, makePhoto);
исправила

2024-03-19 17:38 UTC, kate-baidukova commented on src/presenter/main-presenter.js
> +export default class TripPresenter {
исправила

2024-03-19 17:43 UTC, kate-baidukova commented on src/view/new-point-form-view.js
> +  <div class="event__type-item">
исправила

2024-03-19 18:06 UTC, kate-baidukova commented on src/utils/util.js
> +  return function () {
исправила

2024-03-19 18:24 UTC, kate-baidukova commented on src/utils/util.js
> +      pointDuration = dayjs.duration(timeDiff).format('DD[D] HH[H] mm[M]');
переписала. Надеюсь, верно поняла

2024-03-22 12:21 UTC, kate-baidukova commented on src/presenter/main-presenter.js
> +    this.points = [...this.pointsModel.get()];
get() возвращает массивоподобный объект (array-like который), насколько понимаю. Spread здесь, чтобы скопировать его (исходный) и оперировать данными ниже.

2024-04-05 18:46 UTC, merged